FROM node:24-alpine AS builder

ADD package.json package-lock.json /app/
ADD core/package.json /app/core/
ADD core-client/package.json /app/core-client/
ADD viewer/package.json /app/viewer/

WORKDIR /app
RUN npm ci

ADD core/ /app/core
ADD core-client/ /app/core-client
ADD viewer/ /app/viewer

RUN cd /app/viewer && npm run build
